DROP TABLE "ALL_USER";

CREATE TABLE "ALL_USER" (
	"AU_ID"	VARCHAR2(20)		NOT NULL CONSTRAINT PK_ALL_USER PRIMARY KEY,
	"AU_PWD"	VARCHAR2(20)		NOT NULL,
	"AU_KIND"	VARCHAR2(10)		NOT NULL,
	"AU_ENROLL"	DATE	DEFAULT SYSDATE		NOT NULL,
	"AU_UPDATE"	DATE 			NOT NULL,
	"AU_DEL"	CHAR(1) DEFAULT 'N'		NOT NULL
);

COMMENT ON COLUMN "ALL_USER"."AU_ID" IS '아이디';

COMMENT ON COLUMN "ALL_USER"."AU_PWD" IS '비밀번호';

COMMENT ON COLUMN "ALL_USER"."AU_KIND" IS '회원분류';

COMMENT ON COLUMN "ALL_USER"."AU_ENROLL" IS '가입 날짜';

COMMENT ON COLUMN "ALL_USER"."AU_UPDATE" IS '수정 날짜';

COMMENT ON COLUMN "ALL_USER"."AU_DEL" IS '회원 탈퇴';

DROP TABLE "USER";

CREATE TABLE "USER" (
	"US_ID"	VARCHAR2(20)		NOT NULL CONSTRAINT PK_USER PRIMARY KEY,
	"US_NAME"	VARCHAR2(10)		NOT NULL,
	"US_PHONE"	NUMBER		NOT NULL,
	"US_NICK"	VARCHAR2(20)		NOT NULL,
	"US_EMAIL"	VARCHAR2(30)		NOT NULL,
	"US_BIRTH"	DATE		NOT NULL,
	"US_GEN"		VARCHAR2(1)		NOT NULL,
	"US_PHOTO"	VARCHAR2(50)		NULL,
	"US_INTRO"	VARCHAR2(100)		NULL,
CONSTRAINT PFK_US_ID FOREIGN KEY(US_ID) REFERENCES "ALL_USER"(AU_ID)
);

COMMENT ON COLUMN "USER"."US_ID" IS '아이디';

COMMENT ON COLUMN "USER"."US_NAME" IS '이름';

COMMENT ON COLUMN "USER"."US_PHONE" IS '연락처';

COMMENT ON COLUMN "USER"."US_NICK" IS '닉네임';

COMMENT ON COLUMN "USER"."US_EMAIL" IS '이메일';

COMMENT ON COLUMN "USER"."US_BIRTH" IS '생년월일';

COMMENT ON COLUMN "USER"."US_GEN" IS '성별';

COMMENT ON COLUMN "USER"."US_PHOTO" IS '사진';

COMMENT ON COLUMN "USER"."US_INTRO" IS '인사말';


DROP TABLE "HOSPITAL";

CREATE TABLE "HOSPITAL" (
	"HP_ID"	VARCHAR2(20)		NOT NULL CONSTRAINT PK_HOSPITAL PRIMARY KEY,
	"HP_NAME"	VARCHAR2(20)		NOT NULL,
	"HP_DNAME"	VARCHAR2(20)		NOT NULL,
	"HP_LOC"		VARCHAR2(100)		NOT NULL,
	"HP_INTRO"	VARCHAR2(100)		NULL,
	"HP_PHOTO"	VARCHAR2(50)		NULL,
	"HP_START"	DATE		NOT NULL,
	"HP_END"		DATE	NOT NULL,
	"HP_LUNCH"	DATE	NOT NULL,
CONSTRAINT PFK_HP_ID FOREIGN KEY(HP_ID) REFERENCES "ALL_USER"(AU_ID)
);

COMMENT ON COLUMN "HOSPITAL"."HP_ID" IS '아이디';

COMMENT ON COLUMN "HOSPITAL"."HP_NAME" IS '병원이름';

COMMENT ON COLUMN "HOSPITAL"."HP_DNAME" IS '원장이름';

COMMENT ON COLUMN "HOSPITAL"."HP_INTRO" IS '병원소개';

COMMENT ON COLUMN "HOSPITAL"."HP_PHOTO" IS '대표사진';

COMMENT ON COLUMN "HOSPITAL"."HP_LOC" IS '병원위치';

COMMENT ON COLUMN "HOSPITAL"."HP_START" IS '진료시작시간';

COMMENT ON COLUMN "HOSPITAL"."HP_END" IS '진료종료시간';

COMMENT ON COLUMN "HOSPITAL"."HP_LUNCH" IS '점심시간';

DROP TABLE "HP_MEDICAL";

CREATE TABLE "HP_MEDICAL" (
	"HM_CATE"	VARCHAR2(20) CONSTRAINT PK_HP_MEDICAL PRIMARY KEY,
	"HP_ID"		VARCHAR2(20)	NOT NULL,
	"HM_MIN"	NUMBER		NOT NULL,
	"HM_MAX"	NUMBER		NOT NULL,
	CONSTRAINT FK_HM_ID FOREIGN KEY(HP_ID) REFERENCES HOSPITAL(HP_ID)
);

COMMENT ON COLUMN "HP_MEDICAL"."HM_CATE" IS '진료과목';

COMMENT ON COLUMN "HP_MEDICAL"."HP_ID" IS '병원아이디';

COMMENT ON COLUMN "HP_MEDICAL"."HM_MIN" IS '최소진료비';

COMMENT ON COLUMN "HP_MEDICAL"."HM_MAX" IS '최대진료비';


DROP TABLE "PET";

CREATE TABLE "PET"(
	"PET_NUM"	NUMBER CONSTRAINT PK_PET PRIMARY KEY,
	"PET_NAME"	VARCHAR2(20)		NOT NULL,
	"PET_BIRTH"	DATE		NOT NULL,
	"PET_GEN"	VARCHAR2(1)		NOT NULL,
	"PET_CATE"	VARCHAR2(20)		NOT NULL,
	"PET_SPEC"	VARCHAR2(20)		NOT NULL,
	"PET_WEIGHT"	NUMBER		NOT NULL,
	"PET_VACC"	VARCHAR2(20)		NOT NULL,
	"PET_NEUT"	VARCHAR2(5)		NOT NULL,
	"PET_ADD"	DATE	DEFAULT SYSDATE	NOT NULL,
	"PET_UPDATE"	DATE	DEFAULT SYSDATE NOT NULL,
	"US_ID"	VARCHAR2(20)		NOT NULL,
	"PET_DEL"	CHAR(1)	DEFAULT 'N'	NOT NULL,

	CONSTRAINT FK_US_ID FOREIGN KEY(US_ID) REFERENCES "USER"(US_ID)
);
COMMENT ON COLUMN "PET"."PET_NUM" IS '반려동물 번호';

COMMENT ON COLUMN "PET"."PET_NAME" IS '이름';

COMMENT ON COLUMN "PET"."PET_BIRTH" IS '생년월일';

COMMENT ON COLUMN "PET"."PET_GEN" IS '성별';

COMMENT ON COLUMN "PET"."PET_CATE" IS '종류';

COMMENT ON COLUMN "PET"."PET_SPEC" IS '품종';

COMMENT ON COLUMN "PET"."PET_WEIGHT" IS '체중';

COMMENT ON COLUMN "PET"."PET_VACC" IS '기초 예방 접종 여부';

COMMENT ON COLUMN "PET"."PET_NEUT" IS '중성화 여부';

COMMENT ON COLUMN "PET"."PET_ADD" IS '추가 날짜';

COMMENT ON COLUMN "PET"."PET_UPDATE" IS '수정 날짜';

COMMENT ON COLUMN "PET"."PET_DEL" IS '삭제';

COMMENT ON COLUMN "PET"."US_ID" IS '회원아이디';


DROP TABLE "RESERVATION";

DROP TABLE "RESERVATION";

CREATE TABLE "RESERVATION" (
	"RS_NUM"	NUMBER		NOT NULL CONSTRAINT PK_RS PRIMARY KEY,
	"RS_DATE"	DATE		NOT NULL,
	"RS_MEMO"	VARCHAR(60)		NULL,
	"PET_NUM"	NUMBER		NULL,
	"HM_CATE"	VARCHAR2(20)	NULL,
	"HP_ID"	VARCHAR2(20)	NOT NULL,
	"RS_CAN"		CHAR(1)	DEFAULT 'N'	NOT NULL,
    
CONSTRAINT FK_PET_NUM FOREIGN KEY(PET_NUM) REFERENCES PET(PET_NUM),
CONSTRAINT FK_HM_CATE FOREIGN KEY(HM_CATE) REFERENCES HP_MEDICAL(HM_CATE),
CONSTRAINT FK_HP_ID2 FOREIGN KEY(HP_ID) REFERENCES HOSPITAL(HP_ID)
);

COMMENT ON COLUMN "RESERVATION"."RS_NUM" IS '예약번호';

COMMENT ON COLUMN "RESERVATION"."RS_DATE" IS '예약일시';

COMMENT ON COLUMN "RESERVATION"."RS_MEMO" IS '특이사항';

COMMENT ON COLUMN "RESERVATION"."PET_NUM" IS '반려동물 번호';

COMMENT ON COLUMN "RESERVATION"."HM_CATE" IS '진료과목';

COMMENT ON COLUMN "RESERVATION"."HP_ID" IS '병원아이디';

COMMENT ON COLUMN "RESERVATION"."RS_CAN" IS '예약취소';


DROP TABLE "CALENDER";

CREATE TABLE "CALENDER" (
	"CAL_NUM"	NUMBER			NOT NULL CONSTRAINT PK_CALENDAR PRIMARY KEY,
	"CAL_NAME"	VARCHAR2(20)		NOT NULL,
	"CAL_START"	DATE			NOT NULL,
	"CAL_END"	DATE			NOT NULL,
	"CAL_MEMO"	VARCHAR2(100)		NULL,
	"RS_NUM"	NUMBER			NULL,
	"HP_ID"		VARCHAR2(20)		NULL,
	"US_ID"		VARCHAR2(20)		NULL,
	"CAL_DEL"	CHAR(1)	DEFAULT 'N'	NOT NULL,

CONSTRAINT FK_RS_NUM FOREIGN KEY(RS_NUM) REFERENCES RESERVATION(RS_NUM),
CONSTRAINT FK_HP_ID3 FOREIGN KEY(HP_ID) REFERENCES HOSPITAL(HP_ID),
CONSTRAINT FK_US_ID3 FOREIGN KEY(US_ID) REFERENCES "USER"(US_ID)

);

COMMENT ON COLUMN "CALENDER"."CAL_NUM" IS '일정번호';

COMMENT ON COLUMN "CALENDER"."CAL_NAME" IS '일정이름';

COMMENT ON COLUMN "CALENDER"."CAL_START" IS '시작일시';

COMMENT ON COLUMN "CALENDER"."CAL_END" IS '종료일시';

COMMENT ON COLUMN "CALENDER"."CAL_MEMO" IS '메모';

COMMENT ON COLUMN "CALENDER"."RS_NUM" IS '예약번호';

COMMENT ON COLUMN "CALENDER"."CAL_DEL" IS '일정삭제';

COMMENT ON COLUMN "CALENDER"."HP_ID" IS '병원아이디';

COMMENT ON COLUMN "CALENDER"."US_ID" IS '회원아이디';


DROP TABLE "REVIEW";

CREATE TABLE "REVIEW" (
	"RV_NUM"	NUMBER		NOT NULL CONSTRAINT PK_REVIEW PRIMARY KEY,
	"RV_TITLE"	VARCHAR2(30)		NOT NULL,
	"RV_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"RV_UPDATE"	DATE		NOT NULL,
	"RV_STAR"	NUMBER		NOT NULL,
	"RV_CON"	VARCHAR2(1000)		NOT NULL,
	"HP_ID"		VARCHAR2(20)	NOT NULL,
	"US_ID"		VARCHAR2(20)		NOT NULL,
	"RV_DEL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
CONSTRAINT FK_HP_ID4 FOREIGN KEY(HP_ID) REFERENCES HOSPITAL(HP_ID),
CONSTRAINT FK_US_ID4 FOREIGN KEY(US_ID) REFERENCES "USER"(US_ID)
);

COMMENT ON COLUMN "REVIEW"."RV_NUMBER" IS '후기 번호';

COMMENT ON COLUMN "REVIEW"."RV_TITLE" IS '제목';

COMMENT ON COLUMN "REVIEW"."RV_DATE" IS '작성 날짜';

COMMENT ON COLUMN "REVIEW"."RV_UPDATE" IS '수정 날짜';

COMMENT ON COLUMN "REVIEW"."RV_STAR" IS '별점';

COMMENT ON COLUMN "REVIEW"."RV_CON" IS '내용';

COMMENT ON COLUMN "REVIEW"."RV_DEL" IS '삭제';

COMMENT ON COLUMN "REVIEW"."HP_ID" IS '병원아이디';

COMMENT ON COLUMN "REVIEW"."US_ID" IS '회원아이디';

DROP TABLE "KNOWLEDGE";

CREATE TABLE "KNOWLEDGE" (
	"KN_NUM"	NUMBER CONSTRAINT PK_KNOWLEDGE PRIMARY KEY,
	"KN_TITLE"	VARCHAR2(30)		NOT NULL,
	"KN_CON"	VARCHAR2(1000)		NOT NULL,
	"US_ID"	VARCHAR2(20)		NOT NULL,
	"KN_VIEW"	NUMBER		NOT NULL,
	"KN_DATE"	DATE DEFAULT SYSDATE		NOT NULL,
	"KN_UPDATE"	DATE		NOT NULL,
	"KN_DEL"	CHAR(1)	DEFAULT 'N'	NOT NULL,

CONSTRAINT FK_US_ID5 FOREIGN KEY(US_ID) REFERENCES "USER"(US_ID)
);

COMMENT ON COLUMN "KNOWLEDGE"."KN_NUM" IS '번호';

COMMENT ON COLUMN "KNOWLEDGE"."KN_TITLE" IS '제목';

COMMENT ON COLUMN "KNOWLEDGE"."KN_DATE" IS '작성 날짜';

COMMENT ON COLUMN "KNOWLEDGE"."KN_UPDATE" IS '수정 날짜';

COMMENT ON COLUMN "KNOWLEDGE"."KN_VIEW" IS '조회수';

COMMENT ON COLUMN "KNOWLEDGE"."KN_CON" IS '내용';

COMMENT ON COLUMN "KNOWLEDGE"."KN_DEL" IS '삭제';

COMMENT ON COLUMN "KNOWLEDGE"."US_ID" IS '작성자';

DROP TABLE "KN_REPLY";

CREATE TABLE "KN_REPLY" (
	"KNR_NUM"	NUMBER		CONSTRAINT PK_KNR PRIMARY KEY,
	"KNR_CON"	VARCHAR2(500)		NOT NULL,
	"KNR_DATE"	DATE DEFAULT SYSDATE	NOT NULL,
	"US_ID"	VARCHAR2(20)		NOT NULL,
	"KN_NUM"	NUMBER		NOT NULL,
	"KNR_DEL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
CONSTRAINT FK_US_ID6 FOREIGN KEY(US_ID) REFERENCES "USER"(US_ID),
CONSTRAINT FK_KN_NUM FOREIGN KEY(KN_NUM) REFERENCES "KNOWLEDGE"(KN_NUM)

);

COMMENT ON COLUMN "KN_REPLY"."KNR_NUM" IS '댓글번호';

COMMENT ON COLUMN "KN_REPLY"."KNR_CON" IS '내용';

COMMENT ON COLUMN "KN_REPLY"."KNR_DEL" IS '삭제';

COMMENT ON COLUMN "KN_REPLY"."KNR_DATE" IS '작성 날짜';

COMMENT ON COLUMN "KN_REPLY"."KN_NUM" IS '글 번호';

COMMENT ON COLUMN "KN_REPLY"."US_ID" IS '댓글 작성자';


DROP TABLE "PHOTO";

CREATE TABLE "PHOTO" (
	"PH_NUM"	NUMBER CONSTRAINT PK_PHOTO PRIMARY KEY,
	"PH_ORIG"	VARCHAR2(255)		NOT NULL,
	"PH_CHNG"	VARCHAR2(255)		NOT NULL,
	"PH_PATH"	VARCHAR2(4000)		NOT NULL,
	"PH_UPLOAD"	DATE DEFAULT SYSDATE		NOT NULL,
	"PH_FNUM"	NUMBER		NOT NULL,
	"RV_NUM"	NUMBER		NULL,
	"KN_NUM"	NUMBER		NULL,
	"PH_DEL"		CHAR(1) DEFAULT 'N' NOT NULL,
CONSTRAINT FK_RV_NUM2 FOREIGN KEY(RV_NUM) REFERENCES REVIEW(RV_NUM),
CONSTRAINT FK_KN_NUM2 FOREIGN KEY(KN_NUM) REFERENCES KNOWLEDGE(KN_NUM)
);

COMMENT ON COLUMN "PHOTO"."PH_NUM" IS '사진 번호';

COMMENT ON COLUMN "PHOTO"."PH_ORIG" IS ' 원래 파일 이름';

COMMENT ON COLUMN "PHOTO"."PH_CHNG" IS '바뀐 파일 이름';

COMMENT ON COLUMN "PHOTO"."PH_PATH" IS '파일 경로';

COMMENT ON COLUMN "PHOTO"."PH_UPLOAD" IS '업로드 날짜';

COMMENT ON COLUMN "PHOTO"."PH_FNUM" IS '파일 구분 번호';

COMMENT ON COLUMN "PHOTO"."RV_NUM" IS '후기 번호';

COMMENT ON COLUMN "PHOTO"."KN_NUM" IS '지식글 반호';

COMMENT ON COLUMN "PHOTO"."PH_DEL" IS '사진 삭제';


DROP TABLE "NOTICE";

CREATE TABLE "NOTICE" (
	"NO_NUM"	NUMBER CONSTRAINT PK_NOTICE PRIMARY KEY,
	"NO_TITLE"	VARCHAR2(30)		NOT NULL,
	"NO_DATE"	DATE		NOT NULL,
	"NO_CON"	VARCHAR2(1000)		NOT NULL,
	"AU_ID"		VARCHAR2(20)		NOT NULL,
	"NO_DEL"		CHAR(1)	DEFAULT 'N'	NOT NULL,
CONSTRAINT FK_AU_ID4 FOREIGN KEY(AU_ID) REFERENCES ALL_USER(AU_ID)
);

COMMENT ON COLUMN "NOTICE"."NO_NUM" IS '번호';

COMMENT ON COLUMN "NOTICE"."NO_TITLE" IS '제목';

COMMENT ON COLUMN "NOTICE"."NO_DATE" IS '날짜';

COMMENT ON COLUMN "NOTICE"."NO_CON" IS '내용';

COMMENT ON COLUMN "NOTICE"."NO_DEL" IS '삭제';

COMMENT ON COLUMN "NOTICE"."AU_ID" IS '작성자';

DROP TABLE "PT_COUPON";

CREATE TABLE "PT_COUPON" (
	"PTC_SERIAL"	VARCHAR2(20) CONSTRAINT PK_PT_SHOP PRIMARY KEY,
	"PTC_CNAME"	VARCHAR2(20)		NOT NULL,
	"PTC_USE"	CHAR(1)	DEFAULT 'N' NOT NULL
);

COMMENT ON COLUMN "PT_COUPON"."PTC_SERIAL" IS '일련번호';

COMMENT ON COLUMN "PT_COUPON"."PTC_CNAME" IS '쿠폰이름';

COMMENT ON COLUMN "PT_COUPON"."PTC_USE" IS '쿠폰사용여부';

DROP TABLE "PT_DONATION";

CREATE TABLE "PT_DONATION" (
	"PTD_NUM"	NUMBER CONSTRAINT PK_PTD PRIMARY KEY,
	"PTD_NEEDS"	NUMBER		NULL,
	"PTD_NAME"	VARCHAR2(20)		NULL,
	"PTD_PHOTO"	VARCHAR2(2000)		NULL
);

COMMENT ON COLUMN "PT_DONATION"."PTD_NUM" IS '보호소번호';

COMMENT ON COLUMN "PT_DONATION"."PTD_NEEDS" IS '기부포인트';

COMMENT ON COLUMN "PT_DONATION"."PTD_NAME" IS '보호소이름';

COMMENT ON COLUMN "PT_DONATION"."PTD_PHOTO" IS '보호소사진';


DROP TABLE "POINT";

CREATE TABLE "POINT" (
	"PT_NUM"	NUMBER CONSTRAINT PK_POINT PRIMARY KEY,
	"PT_CUR"	NUMBER		NOT NULL,
	"PT_USE"	NUMBER		NULL,
	"PT_HIS"	VARCHAR2(50)		NOT NULL,
	"PT_ADD"	NUMBER		NULL,
	"PTD_NUM"	NUMBER		NULL,
	"PTC_SERIAL"	VARCHAR2(20)		NOT NULL,
	"US_ID"	VARCHAR2(20)		NOT NULL,
CONSTRAINT FK_PTD_NUM FOREIGN KEY(PTD_NUM) REFERENCES PT_DONATION(PTD_NUM),
CONSTRAINT FK_PTC_SERIAL FOREIGN KEY(PTC_SERIAL) REFERENCES PT_COUPON(PTC_SERIAL),
CONSTRAINT FK_US_ID7 FOREIGN KEY(US_ID) REFERENCES "USER"(US_ID)
);


COMMENT ON COLUMN "POINT"."PT_NUM" IS '포인트기록번호';

COMMENT ON COLUMN "POINT"."PT_CUR" IS '보유포인트';

COMMENT ON COLUMN "POINT"."PT_USE" IS '사용포인트';

COMMENT ON COLUMN "POINT"."PT_HIS" IS '포인트기록';

COMMENT ON COLUMN "POINT"."PT_ADD" IS '적립포인트';

COMMENT ON COLUMN "POINT"."PTD_NUM" IS '보호소번호';

COMMENT ON COLUMN "POINT"."PTC_SERIAL" IS '일련번호';

COMMENT ON COLUMN "POINT"."US_ID" IS '아이디';


DROP TABLE "MESSAGE";

CREATE TABLE "MESSAGE" (
	"MSG_NUM"	NUMBER CONSTRAINT PK_MESSAGE PRIMARY KEY,
	"MSG_TITLE"	VARCHAR2(30)		NOT NULL,
	"MSG_DATE"	DATE		NOT NULL,
	"MSG_CON"	VARCHAR2(800)		NOT NULL,
	"RSG_ID"	VARCHAR2(20)		NOT NULL,
	"SSG_ID"	VARCHAR2(20)		NOT NULL,
	"RSG_DEL"	CHAR(1) DEFAULT 'N'	NOT NULL,
	"SSG_DEL"	CHAR(1)	DEFAULT 'N'		NOT NULL,
	"MSG_STATUS"	VARCHAR2(1)	DEFAULT 'N' NOT NULL,
	
CONSTRAINT FK_US_ID8 FOREIGN KEY(RSG_ID) REFERENCES "USER"(US_ID),
CONSTRAINT FK_US_ID9 FOREIGN KEY(SSG_ID) REFERENCES "USER"(US_ID)
);

COMMENT ON COLUMN "MESSAGE"."MSG_NUM" IS '쪽지 번호';

COMMENT ON COLUMN "MESSAGE"."MSG_TITLE" IS '제목';

COMMENT ON COLUMN "MESSAGE"."MSG_DATE" IS '날짜';

COMMENT ON COLUMN "MESSAGE"."MSG_CON" IS '내용';

COMMENT ON COLUMN "MESSAGE"."RSG_ID" IS '수신자';

COMMENT ON COLUMN "MESSAGE"."SSG_ID" IS '발신자';

COMMENT ON COLUMN "MESSAGE"."RSG_DEL" IS '수신자삭제';

COMMENT ON COLUMN "MESSAGE"."SSG_DEL" IS '발신자삭제';

COMMENT ON COLUMN "MESSAGE"."MSG_STATUS" IS '확인';

