/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-02-18 03:45:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class reservation1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/views/layout.jsp", Long.valueOf(1581477712099L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( request.getContextPath() );
      out.write("/css/index.css\"/>\r\n");
      out.write("<style>\r\n");
      out.write("\t.search_input{width: 150px; padding: 12px 24px; font-size: 14px; line-height: 18px; color: #575756; background-size: 18px 18px; border-radius: 50px; backface-visibility: hidden; border: 1px solid #ffc6c9;position: fixed; right:130px; top: 20px; outline:none;}\r\n");
      out.write("    .search_box1{line-height: 30px; text-align: center; background-color: #ffe3e4; color:#ff4e59;border: 1px solid #fcc6c9; border-radius: 5px; width: 80px; height: 35px;  position: fixed;right: 30px; top: 25px; outline:none;}\r\n");
      out.write("  \t.search_box2{line-height: 30px; text-align: center; background-color: #ffe3e4; color:#ff4e59;border: 1px solid #fcc6c9; border-radius: 5px; width: 80px; height: 35px;  margin-left: 150px; margin-top:20px; outline:none;}\r\n");
      out.write("\r\n");
      out.write("   \t.city-sel{margin-top:100px; margin-left:30px;}\r\n");
      out.write("   \t.animal-sel{margin-top:30px;margin-left:30px;}\r\n");
      out.write("   \t.medi-sel{margin-top:30px; margin-left:30px;}\r\n");
      out.write("   \t\r\n");
      out.write("   \t.medical_departments{width: 200px; padding: 10px; font-size: 14px; line-height: 18px; color: #575756;background-size: 18px 10px; border-radius: 50px; border: 1px solid #ffc6c9;position: fixed; top: 200px; left:220px; outline:none;}\r\n");
      out.write("   \t.hospital_list{border:1px solid #ffc6c9; height: 600px; left:220px; right: 20px; bottom:50px;margin-top:300px; margin-left:20px; margin-right:20px; overflow:scroll;}\r\n");
      out.write("   \t.hospital_list>ul>li{padding:12px;}\r\n");
      out.write("   \t.hospital_list>ul>li::after{content: ''; display:block; border-bottom: 1px solid #ffc6c9; width:100%;}\r\n");
      out.write("   \t#map{width:300px; height:250px; top:350px; margin-left:30px; position:absolute;}\r\n");
      out.write("\r\n");
      out.write("   \t\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t   // 지역 선택\r\n");
      out.write("\t\r\n");
      out.write("\t\t   var f_selbox = [\"서울특별시\",\"인천광역시\",\"대전광역시\",\"광주광역시\",\"대구광역시\",\"울산광역시\",\"부산광역시\",\"경기도\",\"강원도\",\"충청북도\",\"충청남도\",\"전라북도\",\"전라남도\",\"경상북도\",\"경상남도\",\"제주도\"];\r\n");
      out.write("\t\t   var s_selbox = new Array();\r\n");
      out.write("\t\t   s_selbox[0] = [\"강남구\",\"강동구\",\"강북구\",\"강서구\",\"관악구\",\"광진구\",\"구로구\",\"금천구\",\"노원구\",\"도봉구\",\"동대문구\",\"동작구\",\"마포구\",\"서대문구\",\"서초구\",\"성동구\",\"성북구\",\"송파구\",\"양천구\",\"영등포구\",\"용산구\",\"은평구\",\"종로구\",\"중구\",\"중랑구\"];\r\n");
      out.write("\t\t   s_selbox[1] = [\"계양구\",\"남구\",\"남동구\",\"동구\",\"부평구\",\"서구\",\"연수구\",\"중구\",\"강화군\",\"옹진군\"];\r\n");
      out.write("\t\t   s_selbox[2] = [\"대덕구\",\"동구\",\"서구\",\"유성구\",\"중구\"];\r\n");
      out.write("\t\t   s_selbox[3] = [\"광산구\",\"남구\",\"동구\",     \"북구\",\"서구\"];\r\n");
      out.write("\t\t   s_selbox[4] = [\"남구\",\"달서구\",\"동구\",\"북구\",\"서구\",\"수성구\",\"중구\",\"달성군\"];\r\n");
      out.write("\t\t   s_selbox[5] = [\"남구\",\"동구\",\"북구\",\"중구\",\"울주군\"];\r\n");
      out.write("\t\t   s_selbox[6] = [\"강서구\",\"금정구\",\"남구\",\"동구\",\"동래구\",\"부산진구\",\"북구\",\"사상구\",\"사하구\",\"서구\",\"수영구\",\"연제구\",\"영도구\",\"중구\",\"해운대구\",\"기장군\"];\r\n");
      out.write("\t\t   s_selbox[7] = [\"고양시\",\"과천시\",\"광명시\",\"광주시\",\"구리시\",\"군포시\",\"김포시\",\"남양주시\",\"동두천시\",\"부천시\",\"성남시\",\"수원시\",\"시흥시\",\"안산시\",\"안성시\",\"안양시\",\"양주시\",\"오산시\",\"용인시\",\"의왕시\",\"의정부시\",\"이천시\",\"파주시\",\"평택시\",\"포천시\",\"하남시\",\"화성시\",\"가평군\",\"양평군\",\"여주군\",\"연천군\"];\r\n");
      out.write("\t\t   s_selbox[8] = [\"강릉시\",\"동해시\",\"삼척시\",\"속초시\",\"원주시\",\"춘천시\",\"태백시\",\"고성군\",\"양구군\",\"양양군\",\"영월군\",\"인제군\",\"정선군\",\"철원군\",\"평창군\",\"홍천군\",\"화천군\",\"횡성군\"];\r\n");
      out.write("\t\t   s_selbox[9]= [\"제천시\",\"청주시\",\"충주시\",\"괴산군\",\"단양군\",\"보은군\",\"영동군\",\"옥천군\",\"음성군\",\"증평군\",\"진천군\",\"청원군\"];\r\n");
      out.write("\t\t   s_selbox[10] = [\"계룡시\",\"공주시\",\"논산시\",\"보령시\",\"서산시\",\"아산시\",\"천안시\",\"금산군\",\"당진군\",\"부여군\",\"서천군\",\"연기군\",\"예산군\",\"청양군\",\"태안군\",\"홍성군\"];\r\n");
      out.write("\t\t   s_selbox[11] = [\"군산시\",\"김제시\",\"남원시\",\"익산시\",\"전주시\",\"정읍시\",\"고창군\",\"무주군\",\"부안군\",\"순창군\",\"완주군\",\"임실군\",\"장수군\",\"진안군\"];\r\n");
      out.write("\t\t   s_selbox[12] = [\"광양시\",\"나주시\",\"목포시\",\"순천시\",\"여수시\",\"강진군\",\"고흥군\",\"곡성군\",\"구례군\",\"담양군\",\"무안군\",\"보성군\",\"신안군\",\"영광군\",\"영암군\",\"완도군\",\"장성군\",\"장흥군\",\"진도군\",\"함평군\",\"해남군\",\"화순군\"];\r\n");
      out.write("\t\t   s_selbox[13] = [\"경산시\",\"경주시\",\"구미시\",\"김천시\",\"문경시\",\"상주시\",\"안동시\",\"영주시\",\"영천시\",\"포항시\",\"고령군\",\"군위군\",\"봉화군\",\"성주군\",\"영덕군\",\"영양군\",\"예천군\",\"울릉군\",\"울진군\",\"의성군\",\"청도군\",\"청송군\",\"칠곡군\"];\r\n");
      out.write("\t\t   s_selbox[14] = [\"거제시\",\"김해시\",\"마산시\",\"밀양시\",\"사천시\",\"양산시\",\"진주시\",\"진해시\",\"창원시\",\"통영시\",\"거창군\",\"고성군\",\"남해군\",\"산청군\",\"의령군\",\"창녕군\",\"하동군\",\"함안군\",\"함양군\",\"합천군\"];\r\n");
      out.write("\t\t   s_selbox[15] = [\"서귀포시\",\"제주시\",\"남제주군\",\"북제주군\"];\r\n");
      out.write("\r\n");
      out.write(" \t\tfunction init(f){\r\n");
      out.write(" \t\t\tvar f_sel = f.first;\r\n");
      out.write(" \t\t\tvar s_sel = f.second;\r\n");
      out.write(" \t\t\t\r\n");
      out.write(" \t\t\tf_sel.options[0] = new Option(\":: 시/도 ::\", \"\");\r\n");
      out.write(" \t\t\ts_sel.options[0] = new Option(\":: 구/군 ::\", \"\");\r\n");
      out.write(" \t\t\t\r\n");
      out.write(" \t\t\tfor(var i = 0; i < f_selbox.length; i++){\r\n");
      out.write(" \t\t\t\tf_sel.options[i+1] = new Option(f_selbox[i], f_selbox[i]);\r\n");
      out.write(" \t\t\t}\r\n");
      out.write(" \t\t}\r\n");
      out.write(" \t\tfunction initChange(f){\r\n");
      out.write(" \t\t\tvar f_sel = f.first;\r\n");
      out.write(" \t\t\tvar s_sel = f.second;\r\n");
      out.write(" \t\t\t\r\n");
      out.write(" \t\t\tvar sel = f_sel.selectedIndex;\r\n");
      out.write(" \t\t\tfor(var i = s_sel.length; i >= 0; i--){\r\n");
      out.write(" \t\t\t\ts_sel.options[i] = null;\r\n");
      out.write(" \t\t\t}\r\n");
      out.write(" \t\t\t\r\n");
      out.write(" \t\t\ts_sel.options[0] = new Option(\":: 시/도 ::\", \"\");\r\n");
      out.write(" \t\t\t\r\n");
      out.write(" \t\t\tif(sel != 0){\r\n");
      out.write(" \t\t\t\tfor(var i = 0; i < s_selbox[sel-1].length; i++){\r\n");
      out.write(" \t\t\t\t\ts_sel.options[i+1] = new Option(s_selbox[sel-1][i], s_selbox[sel-1][i]);\r\n");
      out.write(" \t\t\t\t}\r\n");
      out.write(" \t\t\t}\r\n");
      out.write(" \t\t}\r\n");
      out.write("\r\n");
      out.write(" \t\t</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body onload = \"init(this.form);\">\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Noto+Sans+KR&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/18fd811fa1.js\" crossorigin=\"anonymous\"></script> <!-- sns아이콘 -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( request.getContextPath() );
      out.write("/css/layout.css\"/> <!-- 작성할 css를 연결 -->\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<header><!-- 헤더 -->\r\n");
      out.write("\t\t<h1 class=\"logo\"></h1>\r\n");
      out.write("\t\t<nav>\r\n");
      out.write("      \t\t<div class=\"login\">\r\n");
      out.write("\t        \t<div><a href=\"#\">로그인</a></div>\r\n");
      out.write("\t        \t<div><a href=\"#\">회원가입</a></div>\r\n");
      out.write("\t      \t</div>\r\n");
      out.write("\t      \t<ul id=\"navigator\">\r\n");
      out.write("\t        \t<li id=\"nav-home\">\r\n");
      out.write("\t         \t\t<a href=\"#\"><span>홈</span></a>\r\n");
      out.write("\t         \t</li>\r\n");
      out.write("\t         \t<li id=\"nav-hospital\">\r\n");
      out.write("\t         \t\t<span>병원 예약</span>\r\n");
      out.write("         \t\t\t<ul class=\"nav2-hospital\" id=\"nav2-hospital\">\r\n");
      out.write("         \t\t\t\t<li><a href=\"#\">병원 검색</a></li>\r\n");
      out.write("\t         \t\t\t<li><a href=\"#\">예약 확인</a></li>\r\n");
      out.write("\t         \t\t\t<li><a href=\"#\">병원 후기</a></li>\r\n");
      out.write("         \t\t\t</ul>\r\n");
      out.write("\t         \t</li>\r\n");
      out.write("\t         \t<li id=\"nav-community\">\r\n");
      out.write("\t         \t\t<span>커뮤니티</span>\r\n");
      out.write("         \t\t\t<ul class=\"nav2-community\" id=\"nav2-community\">\r\n");
      out.write("\t         \t\t\t<li><a href=\"#\">공지사항</a></li>\r\n");
      out.write("\t         \t\t\t<li><a href=\"#\">후기 모아보기</a></li>\r\n");
      out.write("\t         \t\t\t<li><a href=\"#\">지식 공유</a></li>\r\n");
      out.write("         \t\t\t</ul>\r\n");
      out.write("\t         \t</li>\r\n");
      out.write("\t         \t<li id=\"nav-calendar\">\r\n");
      out.write("\t         \t\t<a href=\"#\"><span>캘린더</span></a>\r\n");
      out.write("\t         \t</li>\r\n");
      out.write("\t         \t<li id=\"nav-mypage\">\r\n");
      out.write("\t         \t\t<span>마이페이지</span>\r\n");
      out.write("\t         \t\t<ul class=\"nav2-mypage\" id=\"nav2-mypage\">\r\n");
      out.write("\t\t         \t\t<li><a href=\"#\">내 정보</a></li>\r\n");
      out.write("\t\t         \t\t<li><a href=\"#\">예약 조회</a></li>\r\n");
      out.write("\t\t         \t\t<li><a href=\"#\">포인트샵</a></li>\r\n");
      out.write("\t\t         \t\t<li><a href=\"#\">내가 쓴 글 조회</a></li>\r\n");
      out.write("\t         \t\t</ul>\r\n");
      out.write("\t         \t</li>\r\n");
      out.write("\t      \t</ul>\r\n");
      out.write("\t\t<dl>\r\n");
      out.write("\t    \t<dt class=\"blind\">sns</dt>\r\n");
      out.write("\t        <dd><a href=\"#\"><i class=\"fab fa-facebook-f\"></i></a></dd>\r\n");
      out.write("\t        <dd><a href=\"#\"><i class=\"fab fa-twitter\"></i></a></dd>\r\n");
      out.write("\t        <dd><a href=\"#\"><i class=\"fab fa-youtube\"></i></a></dd>\r\n");
      out.write("\t\t</dl>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<footer></footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<input class=\"search_input\" type=\"search\" placeholder=\"Search\">\r\n");
      out.write("\t\t\t<button class=\"search_box1\">검색</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"city-sel\">\r\n");
      out.write("\t\t\t<form name=\"form\">\r\n");
      out.write("\t\t\t\t<div class=\"select-box\">\r\n");
      out.write("\t\t\t\t\t<select id=\"first\" onchange=\"initChange(this.form);\"></select>\r\n");
      out.write("\t\t\t\t\t<select id=\"second\"></select>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"animal-sel\">\r\n");
      out.write("\t\t\t<div class=\"select-box\">\r\n");
      out.write("\t\t\t\t<select>\r\n");
      out.write("\t\t\t\t\t<option>동물 선택</option>\r\n");
      out.write("\t\t\t\t\t<option>동물 선택</option>\r\n");
      out.write("\t\t\t\t\t<option>동물 선택</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t</div>\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"map\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=f3549269f64d3486484fc870940fc9dd\"></script>\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\tvar container = document.getElementById('map');\r\n");
      out.write("\t\t\tvar options = {\r\n");
      out.write("\t\t\t\tcenter: new kakao.maps.LatLng(33.450701, 126.570667),\r\n");
      out.write("\t\t\t\tlevel: 3\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\r\n");
      out.write("\t\t\tvar map = new kakao.maps.Map(container, options);\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"medi-sel\">\r\n");
      out.write("\t\t\t<div class=\"select-box\">\r\n");
      out.write("\t\t\t\t<select>\r\n");
      out.write("\t\t\t\t\t<option value=\"\" disabled>건강검진</option>\r\n");
      out.write("\t\t\t\t\t<option>기초 종합검진</option>\r\n");
      out.write("\t\t\t\t\t<option>복합 종합검진</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"\" disabled>혈액검사</option>\r\n");
      out.write("\t\t\t\t\t<option>기초 혈액검사</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"\" disabled>안과검진</option>\r\n");
      out.write("\t\t\t\t\t<option>안과검진</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"\" disabled>예방접종</option>\r\n");
      out.write("\t\t\t\t\t<option>코로나</option>\r\n");
      out.write("\t\t\t\t\t<option>켄넬로프</option>\r\n");
      out.write("\t\t\t\t\t<option>반려견 종합백신</option>\r\n");
      out.write("\t\t\t\t\t<option>광견병</option>\r\n");
      out.write("\t\t\t\t\t<option>인플루엔자</option>\r\n");
      out.write("\t\t\t\t\t<option>반려묘 종합백신</option>\r\n");
      out.write("\t\t\t\t\t<option>항체가검사</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"\" disabled>치과</option>\r\n");
      out.write("\t\t\t\t\t<option>스케일링</option>\r\n");
      out.write("\t\t\t\t\t<option>발치</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"\" disabled>피부과</option>\r\n");
      out.write("\t\t\t\t\t<option>곰팡이균 검사</option>\r\n");
      out.write("\t\t\t\t\t<option>알러지 검사</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"\" disabled>키트검사</option>\r\n");
      out.write("\t\t\t\t\t<option>심장사상충 검사</option>\r\n");
      out.write("\t\t\t\t\t<option>혈액형 검사</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"\" disabled>내시경</option>\r\n");
      out.write("\t\t\t\t\t<option>내시경</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"\" disabled>초음파</option>\r\n");
      out.write("\t\t\t\t\t<option>초음파</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"\" disabled>중성화 수술</option>\r\n");
      out.write("\t\t\t\t\t<option>수컷</option>\r\n");
      out.write("\t\t\t\t\t<option>암컷</option>\r\n");
      out.write("\t\t\t\t\t<option>잠복고환</option>\r\n");
      out.write("\t\t\t\t\t<option>기타</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<button class=\"search_box2\">병원 검색</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"hospital_list\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\tA 동물병원\r\n");
      out.write("\t\t\t\t\t</a><br><br>\r\n");
      out.write("\t\t\t\t\t서울특별시 광진구 123-45 A 동물병원 \r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\tB 동물병원\r\n");
      out.write("\t\t\t\t\t</a><br><br>\r\n");
      out.write("\t\t\t\t\t서울특별시 광진구 123-55 B 동물병원<br>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\tB 동물병원\r\n");
      out.write("\t\t\t\t\t</a><br><br>\r\n");
      out.write("\t\t\t\t\t서울특별시 광진구 123-55 B 동물병원<br>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\tB 동물병원\r\n");
      out.write("\t\t\t\t\t</a><br><br>\r\n");
      out.write("\t\t\t\t\t서울특별시 광진구 123-55 B 동물병원<br>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\tB 동물병원\r\n");
      out.write("\t\t\t\t\t</a><br><br>\r\n");
      out.write("\t\t\t\t\t서울특별시 광진구 123-55 B 동물병원<br>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\tB 동물병원\r\n");
      out.write("\t\t\t\t\t</a><br><br>\r\n");
      out.write("\t\t\t\t\t서울특별시 광진구 123-55 B 동물병원<br>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\tB 동물병원\r\n");
      out.write("\t\t\t\t\t</a><br><br>\r\n");
      out.write("\t\t\t\t\t서울특별시 광진구 123-55 B 동물병원<br>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\tB 동물병원\r\n");
      out.write("\t\t\t\t\t</a><br><br>\r\n");
      out.write("\t\t\t\t\t서울특별시 광진구 123-55 B 동물병원<br>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\tB 동물병원\r\n");
      out.write("\t\t\t\t\t</a><br><br>\r\n");
      out.write("\t\t\t\t\t서울특별시 광진구 123-55 B 동물병원<br>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\tB 동물병원\r\n");
      out.write("\t\t\t\t\t</a><br><br>\r\n");
      out.write("\t\t\t\t\t서울특별시 광진구 123-55 B 동물병원<br>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
